language: c
os: linux # Jobs are on Linux unless specified otherwise
dist: trusty # Jobs are on Trusty unless specified otherwise
sudo: false

matrix:
  include:
    # Clang 3.5
    - env: COMPILER=clang-3.5
      addons: { apt: { packages: ["clang-3.5", "cmake"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.5"] } }

install:
  - ${CC} --version
  - cmake --version

before_script:
  # Set up the build directory
  - cmake -Bbuild -H. -DCMAKE_C_COMPILER=${COMPILER} -DCMAKE_C_FLAGS="-fsanitize=address -fsanitize=undefined" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address -fsanitize=undefined"


script:
  # Check for common formatting errors.
  - sources=($(find include src -name "*.h" -or -name "*.c"))
  - LANG=POSIX grep $'\r'                   "${sources[@]}"; [[ $? == 1 ]] || exit 1 # '\r' (CR) character
  - LANG=POSIX grep $'\t'                   "${sources[@]}"; [[ $? == 1 ]] || exit 1 # Tab character
  - LANG=POSIX grep '[[:blank:]]$'          "${sources[@]}"; [[ $? == 1 ]] || exit 1 # Trailing whitespace

  ############################################################################
  # Build and run the tests
  ############################################################################
  - cmake --build build && cd build && ctest --output-on-failure -j2
